-- =============================================================================
-- Promed: Telegram account-link codes and claim RPC
-- =============================================================================
-- Stores short-lived, single-use codes generated by the Telegram bot so a
-- Supabase user can complete account linking from the web app.
--
-- Flow:
--   1. User sends /link in Telegram, bot inserts (code, chat_id, expires_at).
--   2. User pastes that 6-char code into Promed → Settings → Telegram.
--   3. The web app calls public.claim_telegram_link(code) which:
--        - marks the code used (with the Supabase auth.uid())
--        - upserts a row in public.telegram_links tying chat_id → user_id
--      Returns 'ok' (or raises 'invalid code' on bad/expired codes).
--
-- Both columns are nullable because:
--   - chat_id is set at code-generation time by the bot (Telegram side).
--   - user_id is set at claim time by the RPC (web-app side).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.telegram_link_codes (
    code TEXT PRIMARY KEY CHECK (code ~ '^[A-Z0-9]{6}$'),
    chat_id BIGINT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Idempotent column widening for existing installs:
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema='public' AND table_name='telegram_link_codes' AND column_name='user_id'
    ) AND (SELECT is_nullable FROM information_schema.columns
           WHERE table_schema='public' AND table_name='telegram_link_codes' AND column_name='user_id') = 'NO' THEN
        ALTER TABLE public.telegram_link_codes ALTER COLUMN user_id DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema='public' AND table_name='telegram_link_codes' AND column_name='user_id'
    ) AND EXISTS (SELECT 1 FROM pg_constraint WHERE conname='telegram_link_codes_user_id_fkey') THEN
        ALTER TABLE public.telegram_link_codes DROP CONSTRAINT telegram_link_codes_user_id_fkey;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema='public' AND table_name='telegram_link_codes' AND column_name='chat_id'
    ) THEN
        ALTER TABLE public.telegram_link_codes ADD COLUMN chat_id BIGINT;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.foreign_keys
        WHERE constraint_schema='public' AND table_name='telegram_link_codes'
              AND constraint_name='telegram_link_codes_user_id_fkey'
    ) AND NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname='telegram_link_codes_user_id_fkey'
    ) THEN
        ALTER TABLE public.telegram_link_codes
            ADD CONSTRAINT telegram_link_codes_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
END
$$;

ALTER TABLE public.telegram_link_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS telegram_link_codes_select ON public.telegram_link_codes;
CREATE POLICY telegram_link_codes_select
    ON public.telegram_link_codes
    FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.claim_telegram_link(p_code TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_chat_id BIGINT;
    v_user_id UUID;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'not authenticated';
    END IF;

    -- Lock + validate the code in a single round trip.
    UPDATE public.telegram_link_codes
    SET used_at = NOW(),
        user_id = auth.uid()
    WHERE code = p_code
      AND used_at IS NULL
      AND expires_at > NOW()
    RETURNING chat_id INTO v_chat_id;

    IF v_chat_id IS NULL THEN
        RAISE EXCEPTION 'invalid code';
    END IF;

    -- Persist the chat_id ↔ user_id binding so future bot messages from this
    -- chat are routed to this user.
    v_user_id := auth.uid();
    INSERT INTO public.telegram_links (chat_id, user_id, last_seen_at)
    VALUES (v_chat_id, v_user_id, NOW())
    ON CONFLICT (chat_id) DO UPDATE
        SET user_id = EXCLUDED.user_id,
            last_seen_at = EXCLUDED.last_seen_at;

    RETURN 'ok';
END;
$$;

REVOKE ALL ON FUNCTION public.claim_telegram_link(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_telegram_link(TEXT) TO authenticated;
