import jsPDF from 'jspdf'
import 'jspdf-autotable'

/* ───── Font cache (loaded once, reused) ───── */
let _fontCache = null

async function loadArabicFont() {
  if (_fontCache) return _fontCache
  try {
    const [regular, bold] = await Promise.all([
      fetch('/fonts/Amiri-Regular.ttf').then(r => r.arrayBuffer()),
      fetch('/fonts/Amiri-Bold.ttf').then(r => r.arrayBuffer()),
    ])
    _fontCache = {
      regular: arrayBufferToBase64(regular),
      bold: arrayBufferToBase64(bold),
    }
    return _fontCache
  } catch {
    return null
  }
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer)
  let binary = ''
  const chunkSize = 8192
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize)
    binary += String.fromCharCode.apply(null, chunk)
  }
  return btoa(binary)
}

function registerFont(doc, fontData) {
  if (!fontData) return false
  doc.addFileToVFS('Amiri-Regular.ttf', fontData.regular)
  doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal')
  doc.addFileToVFS('Amiri-Bold.ttf', fontData.bold)
  doc.addFont('Amiri-Bold.ttf', 'Amiri', 'bold')
  return true
}

/* ───── Helpers ───── */

function hasArabic(text) {
  return /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/.test(text || '')
}

function fmt(n) {
  return (Number(n) || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function fmtDate(d) {
  if (!d) return '—'
  return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

// Bilingual label maps
const labels = {
  en: {
    invoice: 'INVOICE',
    invoiceNumber: 'Invoice #',
    date: 'Date',
    dueDate: 'Due Date',
    status: 'Status',
    paid: 'PAID',
    outstanding: 'OUTSTANDING',
    overdue: 'OVERDUE',
    billTo: 'Bill To',
    from: 'From',
    description: 'Description',
    model: 'Model',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    amount: 'Amount',
    subtotal: 'Subtotal',
    paidAmount: 'Paid',
    balanceDue: 'Balance Due',
    paymentHistory: 'Payment History',
    paymentDate: 'Date',
    paymentAmount: 'Amount',
    paymentMethod: 'Method',
    reference: 'Reference',
    notes: 'Notes',
    terms: 'Payment Terms',
    thankYou: 'Thank you for your business!',
    generatedBy: 'Generated by Promed',
    page: 'Page',
    termsNet30: 'Payment is due within 30 days of invoice date.',
    cash: 'Cash', cheque: 'Cheque', bankTransfer: 'Bank Transfer', card: 'Card', other: 'Other',
  },
  ar: {
    invoice: 'فـاتـورة',
    invoiceNumber: 'رقم الفاتورة',
    date: 'التاريخ',
    dueDate: 'تاريخ الاستحقاق',
    status: 'الحالة',
    paid: 'مدفوعة',
    outstanding: 'مستحقة',
    overdue: 'متأخرة',
    billTo: 'فاتورة إلى',
    from: 'من',
    description: 'الوصف',
    model: 'الموديل',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    amount: 'المبلغ',
    subtotal: 'المجموع الفرعي',
    paidAmount: 'المدفوع',
    balanceDue: 'المبلغ المتبقي',
    paymentHistory: 'سجل الدفعات',
    paymentDate: 'التاريخ',
    paymentAmount: 'المبلغ',
    paymentMethod: 'طريقة الدفع',
    reference: 'المرجع',
    notes: 'ملاحظات',
    terms: 'شروط الدفع',
    thankYou: '!شكراً لتعاملكم معنا',
    generatedBy: 'Promed تم الإنشاء بواسطة',
    page: 'صفحة',
    termsNet30: '.يستحق الدفع خلال 30 يوم من تاريخ الفاتورة',
    cash: 'نقداً', cheque: 'شيك', bankTransfer: 'تحويل بنكي', card: 'بطاقة', other: 'أخرى',
  },
}

/* ───── Colors ───── */
const COLORS = {
  primary: [30, 64, 175],      // blue-800
  primaryLight: [59, 130, 246], // blue-500
  accent: [239, 246, 255],      // blue-50
  white: [255, 255, 255],
  text: [17, 24, 39],           // gray-900
  muted: [107, 114, 128],       // gray-500
  light: [243, 244, 246],       // gray-100
  border: [209, 213, 219],      // gray-300
  green: [22, 163, 74],         // green-600
  red: [220, 38, 38],           // red-600
  amber: [217, 119, 6],         // amber-600
}

/* ───── Main function ───── */

/**
 * Generate a professional bilingual PDF invoice
 * @param {Object} transaction - The transaction data
 * @param {Object} options - Settings (currency, language, company info, payments)
 */
export async function generateInvoice(transaction, options = {}) {
  const {
    companyName = 'Promed',
    companyAddress = '',
    companyPhone = '',
    companyEmail = '',
    invoicePrefix = 'INV',
    currency = 'EGP',
    language = 'en',
    payments = [],
  } = options

  const isAr = language === 'ar'
  const L = labels[isAr ? 'ar' : 'en']
  const fontData = await loadArabicFont()

  const doc = new jsPDF({ putOnlyUsedFonts: true })
  const hasFont = registerFont(doc, fontData)

  // Choose font: use Amiri if available (supports Arabic), else fallback to helvetica
  const fontFamily = hasFont ? 'Amiri' : 'helvetica'
  const setFont = (style = 'normal', size = 10) => {
    doc.setFont(fontFamily, style)
    doc.setFontSize(size)
  }

  const pw = doc.internal.pageSize.getWidth()   // ~210
  const ph = doc.internal.pageSize.getHeight()   // ~297
  const marginL = 20
  const marginR = 20
  const contentW = pw - marginL - marginR

  // Text helper: auto-align based on language
  const txt = (text, x, y, opts = {}) => {
    const str = String(text ?? '')
    doc.text(str, x, y, opts)
  }

  // Right-side x position
  const rX = pw - marginR

  /* ═══════════════════════════════════════════
     HEADER — Blue bar with logo area + invoice title
     ═══════════════════════════════════════════ */
  // Primary header bar
  doc.setFillColor(...COLORS.primary)
  doc.rect(0, 0, pw, 44, 'F')

  // Thin accent line
  doc.setFillColor(...COLORS.primaryLight)
  doc.rect(0, 44, pw, 2, 'F')

  // Company name (left/right based on lang)
  doc.setTextColor(...COLORS.white)
  setFont('bold', 26)
  if (isAr) {
    txt(companyName, rX, 28, { align: 'right' })
  } else {
    txt(companyName, marginL, 28)
  }

  // Invoice title (opposite side)
  setFont('bold', 18)
  if (isAr) {
    txt(L.invoice, marginL, 22)
  } else {
    txt(L.invoice, rX, 22, { align: 'right' })
  }

  // Invoice number under title
  const invoiceNum = transaction.invoice_number ||
    `${invoicePrefix}-${String(transaction.transaction_id).padStart(5, '0')}`
  setFont('normal', 11)
  doc.setTextColor(200, 220, 255)
  if (isAr) {
    txt(invoiceNum, marginL, 32)
  } else {
    txt(invoiceNum, rX, 32, { align: 'right' })
  }

  /* ═══════════════════════════════════════════
     INVOICE META — Date, Due Date, Status
     ═══════════════════════════════════════════ */
  let y = 56

  // Status badge
  const remaining = parseFloat(transaction.remaining_amount || 0)
  const isPaid = remaining <= 0
  const dueDate = transaction.due_date
  const isOverdue = !isPaid && dueDate && new Date(dueDate) < new Date()
  const statusText = isPaid ? L.paid : (isOverdue ? L.overdue : L.outstanding)
  const statusColor = isPaid ? COLORS.green : (isOverdue ? COLORS.red : COLORS.amber)

  // Meta info boxes in a row
  const metaBoxW = contentW / 4
  const metaItems = [
    { label: L.invoiceNumber, value: invoiceNum },
    { label: L.date, value: fmtDate(transaction.transaction_date) },
    { label: L.dueDate, value: fmtDate(dueDate) },
    { label: L.status, value: statusText, color: statusColor },
  ]

  metaItems.forEach((item, i) => {
    const boxX = marginL + (i * metaBoxW)
    // Light background
    doc.setFillColor(...COLORS.light)
    doc.roundedRect(boxX + 1, y, metaBoxW - 2, 22, 2, 2, 'F')
    // Label
    doc.setTextColor(...COLORS.muted)
    setFont('normal', 8)
    txt(item.label, boxX + metaBoxW / 2, y + 8, { align: 'center' })
    // Value
    doc.setTextColor(...(item.color || COLORS.text))
    setFont('bold', 10)
    txt(item.value, boxX + metaBoxW / 2, y + 17, { align: 'center' })
  })

  /* ═══════════════════════════════════════════
     BILL TO / FROM — Two column section
     ═══════════════════════════════════════════ */
  y += 32

  const clientName = transaction.clients?.client_name || transaction.suppliers?.supplier_name || '—'
  const contactInfo = transaction.clients?.contact_info || transaction.suppliers?.contact_info || ''

  const halfW = contentW / 2

  // Bill To section
  const billToX = isAr ? (marginL + halfW + 10) : marginL
  const fromX = isAr ? marginL : (marginL + halfW + 10)

  // Bill To
  doc.setFillColor(...COLORS.accent)
  doc.roundedRect(billToX, y, halfW - 5, 30, 2, 2, 'F')
  doc.setDrawColor(...COLORS.primaryLight)
  doc.setLineWidth(0.5)
  doc.roundedRect(billToX, y, halfW - 5, 30, 2, 2, 'S')

  doc.setTextColor(...COLORS.primaryLight)
  setFont('bold', 9)
  txt(L.billTo, billToX + 8, y + 9)
  doc.setTextColor(...COLORS.text)
  setFont('bold', 12)
  txt(clientName, billToX + 8, y + 19)
  if (contactInfo) {
    doc.setTextColor(...COLORS.muted)
    setFont('normal', 9)
    txt(contactInfo, billToX + 8, y + 26)
  }

  // From (company)
  doc.setFillColor(...COLORS.light)
  doc.roundedRect(fromX, y, halfW - 5, 30, 2, 2, 'F')

  doc.setTextColor(...COLORS.muted)
  setFont('bold', 9)
  txt(L.from, fromX + 8, y + 9)
  doc.setTextColor(...COLORS.text)
  setFont('bold', 12)
  txt(companyName, fromX + 8, y + 19)
  if (companyAddress || companyPhone || companyEmail) {
    doc.setTextColor(...COLORS.muted)
    setFont('normal', 9)
    const info = [companyAddress, companyPhone, companyEmail].filter(Boolean).join(' · ')
    txt(info, fromX + 8, y + 26)
  }

  /* ═══════════════════════════════════════════
     LINE ITEMS TABLE
     ═══════════════════════════════════════════ */
  y += 40

  // Thin divider
  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(marginL, y, pw - marginR, y)
  y += 5

  const productName = transaction.products?.product_name || 'Product / Service'
  const modelName = transaction.products?.model || ''
  const qty = transaction.quantity || 1
  const unitPrice = parseFloat(transaction.unit_price || 0)
  const totalAmount = parseFloat(transaction.total_amount || 0)

  const fmtCur = (n) => {
    const val = fmt(n)
    return isAr ? `${val} ${currency}` : `${currency} ${val}`
  }

  const tableHead = isAr
    ? [[L.amount, L.unitPrice, L.qty, L.model, L.description]]
    : [[L.description, L.model, L.qty, L.unitPrice, L.amount]]

  const tableRow = isAr
    ? [fmtCur(totalAmount), fmtCur(unitPrice), String(qty), modelName, productName]
    : [productName, modelName, String(qty), fmtCur(unitPrice), fmtCur(totalAmount)]

  doc.autoTable({
    startY: y,
    head: tableHead,
    body: [tableRow],
    theme: 'plain',
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      fontSize: 10,
      cellPadding: { top: 5, bottom: 5, left: 6, right: 6 },
      font: fontFamily,
    },
    bodyStyles: {
      fontSize: 10,
      cellPadding: { top: 6, bottom: 6, left: 6, right: 6 },
      textColor: COLORS.text,
      font: fontFamily,
    },
    alternateRowStyles: {
      fillColor: COLORS.light,
    },
    styles: {
      lineColor: COLORS.border,
      lineWidth: 0.2,
      overflow: 'linebreak',
      font: fontFamily,
      halign: isAr ? 'right' : 'left',
    },
    columnStyles: isAr
      ? {
          0: { cellWidth: 38, halign: 'left' },
          1: { cellWidth: 38, halign: 'left' },
          2: { cellWidth: 22, halign: 'center' },
          3: { cellWidth: 32, halign: 'right' },
          4: { cellWidth: 'auto', halign: 'right' },
        }
      : {
          0: { cellWidth: 'auto' },
          1: { cellWidth: 32 },
          2: { cellWidth: 22, halign: 'center' },
          3: { cellWidth: 38, halign: 'right' },
          4: { cellWidth: 38, halign: 'right' },
        },
    margin: { left: marginL, right: marginR },
    tableWidth: contentW,
  })

  /* ═══════════════════════════════════════════
     TOTALS SECTION
     ═══════════════════════════════════════════ */
  y = doc.lastAutoTable.finalY + 8

  const totalsW = 90
  const totalsX = isAr ? marginL : (pw - marginR - totalsW)

  // Background box
  doc.setFillColor(...COLORS.light)
  doc.roundedRect(totalsX, y, totalsW, 42, 2, 2, 'F')

  // Subtotal
  doc.setTextColor(...COLORS.muted)
  setFont('normal', 10)
  txt(L.subtotal, totalsX + 6, y + 10)
  doc.setTextColor(...COLORS.text)
  setFont('normal', 10)
  txt(fmtCur(totalAmount), totalsX + totalsW - 6, y + 10, { align: 'right' })

  // Paid
  doc.setTextColor(...COLORS.muted)
  setFont('normal', 10)
  txt(L.paidAmount, totalsX + 6, y + 21)
  doc.setTextColor(...COLORS.green)
  setFont('normal', 10)
  txt(`- ${fmtCur(transaction.paid_amount || 0)}`, totalsX + totalsW - 6, y + 21, { align: 'right' })

  // Divider inside totals
  doc.setDrawColor(...COLORS.border)
  doc.line(totalsX + 4, y + 26, totalsX + totalsW - 4, y + 26)

  // Balance Due
  doc.setTextColor(...(isPaid ? COLORS.green : COLORS.red))
  setFont('bold', 12)
  txt(L.balanceDue, totalsX + 6, y + 37)
  txt(fmtCur(remaining), totalsX + totalsW - 6, y + 37, { align: 'right' })

  /* ═══════════════════════════════════════════
     PAYMENT HISTORY (if payments exist)
     ═══════════════════════════════════════════ */
  const txPayments = payments.length > 0 ? payments : (transaction.payments || [])

  if (txPayments.length > 0) {
    y += 54

    // Check if we need a new page
    if (y > ph - 80) {
      doc.addPage()
      y = 20
    }

    doc.setTextColor(...COLORS.primary)
    setFont('bold', 11)
    txt(L.paymentHistory, marginL, y)
    y += 4

    const methodLabel = (m) => {
      const key = (m || 'cash').toLowerCase().replace(/\s/g, '')
      const map = { cash: L.cash, cheque: L.cheque, bank_transfer: L.bankTransfer, banktransfer: L.bankTransfer, card: L.card }
      return map[key] || m || L.cash
    }

    const payHead = isAr
      ? [[L.reference, L.paymentMethod, L.paymentAmount, L.paymentDate]]
      : [[L.paymentDate, L.paymentAmount, L.paymentMethod, L.reference]]

    const payBody = txPayments.map(p => {
      const row = [
        fmtDate(p.payment_date),
        fmtCur(p.amount),
        methodLabel(p.payment_method),
        p.reference_number || '—',
      ]
      return isAr ? row.reverse() : row
    })

    doc.autoTable({
      startY: y,
      head: payHead,
      body: payBody,
      theme: 'plain',
      headStyles: {
        fillColor: COLORS.primaryLight,
        textColor: COLORS.white,
        fontStyle: 'bold',
        fontSize: 9,
        cellPadding: { top: 4, bottom: 4, left: 5, right: 5 },
        font: fontFamily,
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: { top: 4, bottom: 4, left: 5, right: 5 },
        textColor: COLORS.text,
        font: fontFamily,
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      styles: {
        lineColor: COLORS.border,
        lineWidth: 0.15,
        font: fontFamily,
        halign: isAr ? 'right' : 'left',
      },
      margin: { left: marginL, right: marginR },
      tableWidth: contentW,
    })

    y = doc.lastAutoTable.finalY + 6
  } else {
    y += 54
  }

  /* ═══════════════════════════════════════════
     PAYMENT TERMS NOTE
     ═══════════════════════════════════════════ */
  if (y > ph - 60) {
    doc.addPage()
    y = 20
  }

  const termsMap = {
    cod: 'COD', net_15: 'Net 15', net_30: 'Net 30', net_60: 'Net 60', net_90: 'Net 90',
  }
  const termText = transaction.payment_terms && transaction.payment_terms !== 'none'
    ? `${L.terms}: ${termsMap[transaction.payment_terms] || transaction.payment_terms}`
    : ''

  if (termText) {
    doc.setTextColor(...COLORS.muted)
    setFont('normal', 9)
    txt(termText, isAr ? rX : marginL, y, isAr ? { align: 'right' } : {})
    y += 8
  }

  /* ═══════════════════════════════════════════
     FOOTER — Thank you + contact
     ═══════════════════════════════════════════ */
  const footerY = ph - 25

  // Divider line
  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(marginL, footerY - 8, pw - marginR, footerY - 8)

  // Thank you
  doc.setTextColor(...COLORS.primary)
  setFont('bold', 11)
  txt(L.thankYou, pw / 2, footerY, { align: 'center' })

  // Contact info
  if (companyEmail || companyPhone) {
    doc.setTextColor(...COLORS.muted)
    setFont('normal', 8)
    const contactLine = [companyEmail, companyPhone].filter(Boolean).join('  ·  ')
    txt(contactLine, pw / 2, footerY + 6, { align: 'center' })
  }

  // Generated by
  doc.setTextColor(180, 180, 180)
  setFont('normal', 7)
  txt(L.generatedBy, pw / 2, footerY + 13, { align: 'center' })

  /* ═══════════════════════════════════════════
     SAVE
     ═══════════════════════════════════════════ */
  const fileName = `invoice-${invoiceNum}.pdf`
  doc.save(fileName)
  return fileName
}

/**
 * Generate invoices for multiple transactions
 */
export async function generateBulkInvoices(transactions, options = {}) {
  for (const transaction of transactions) {
    await generateInvoice(transaction, options)
  }
}
